# Generated by Django 3.2.15 on 2022-09-11 06:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=None, max_length=255, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'FOLDER'), (2, 'FILE')])),
                ('date', models.DateTimeField()),
                ('size', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.filesystem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
