# Generated by Django 3.2.15 on 2022-09-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20220912_2113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesystem",
            name="id",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
